using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Aspenlaub.Net.GitHub.CSharp.Pegh.Entities;
using Aspenlaub.Net.GitHub.CSharp.Pegh.Extensions;
using Aspenlaub.Net.GitHub.CSharp.Pegh.Interfaces;
using Autofac;
using Cake.Frosting;

namespace Aspenlaub.Net.GitHub.CSharp.Shatilaya.Tasks;

[TaskName("EnsureShatilayaCmd")]
[TaskDescription("Create or update shatilaya.cmd")]
public class EnsureShatilayaCmdTask : AsyncFrostingTask<ShatilayaContext> {
    public override async Task RunAsync(ShatilayaContext context) {
        var errorsAndInfos = new ErrorsAndInfos();
        IFolder workingFolder = await context.Container.Resolve<IFolderResolver>().ResolveAsync("$(Shatilaya)", errorsAndInfos);
        if (errorsAndInfos.AnyErrors()) {
            throw new Exception(errorsAndInfos.ErrorsToString());
        }
        var executableFullNames = Directory.GetFiles(workingFolder.FullName, "*Shatilaya*.exe").ToList();
        if (executableFullNames.Count != 1) {
            throw new Exception("Shatilaya executable not found or not unique");
        }

        List<string> lines = [
            $"cd {workingFolder.FullName}",
            $"{executableFullNames[0]} --repository {context.RepositoryFolder.FullName} %*",
            "pause"
        ];
        string contents = string.Join("\r\n", lines);
        string fileName = context.RepositoryFolder.FullName + @"\\shatilaya.cmd";
        if (!File.Exists(fileName) || contents != await File.ReadAllTextAsync(fileName)) {
            await File.WriteAllTextAsync(fileName, contents);
        }

        fileName = context.RepositoryFolder.FullName + @"\\.gitignore";
        if (!File.Exists(fileName)) {
            throw new FileNotFoundException(fileName);
        }

        lines = (await File.ReadAllLinesAsync(fileName)).ToList();
        if (lines.Any(x => x.Contains("shatilaya.cmd"))) {
            return;
        }

        if (!string.IsNullOrEmpty(lines[lines.Count - 1])) {
            lines.Add("");
        }
        lines.Add("# Generated by the little things");
        lines.Add("shatilaya.cmd");
        lines.Add("");
        await File.WriteAllLinesAsync(fileName, lines);
    }
}
