//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.Shatilaya.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.Shatilaya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string FailedToCopy {
            get {
                return ResourceManager.GetString("FailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename &quot;{0}&quot; into &quot;{1}&quot;.
        /// </summary>
        internal static string FailedToRename {
            get {
                return ResourceManager.GetString("FailedToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; could not be created.
        /// </summary>
        internal static string FolderCouldNotBeCreated {
            get {
                return ResourceManager.GetString("FolderCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; is obsolete.
        /// </summary>
        internal static string FolderIsObsolete {
            get {
                return ResourceManager.GetString("FolderIsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete &apos;DeveloperSettings&apos;. Please update &quot;{0}&quot; in your SecretRepository.
        /// </summary>
        internal static string IncompleteDeveloperSettings {
            get {
                return ResourceManager.GetString("IncompleteDeveloperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no valid XML in &quot;{0}&quot;.
        /// </summary>
        internal static string InvalidXmlFile {
            get {
                return ResourceManager.GetString("InvalidXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;DeveloperSettings&apos; secret. Open &quot;{0}&quot; in SecretSamples, modify it and save it in SecretRepository.
        /// </summary>
        internal static string MissingDeveloperSettings {
            get {
                return ResourceManager.GetString("MissingDeveloperSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one element was not found in &apos;{0}&apos;.
        /// </summary>
        internal static string MissingElementInProjectFile {
            get {
                return ResourceManager.GetString("MissingElementInProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No apikey was found for this source.
        /// </summary>
        internal static string NoApiKeyFound {
            get {
                return ResourceManager.GetString("NoApiKeyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; does not contain any packages.
        /// </summary>
        internal static string NoPackageFilesFound {
            get {
                return ResourceManager.GetString("NoPackageFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed &quot;{0}&quot; does not provide package &quot;{1}&quot;.
        /// </summary>
        internal static string NoRemotePackageFilesFound {
            get {
                return ResourceManager.GetString("NoRemotePackageFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been updated.
        /// </summary>
        internal static string NuSpecFileUpdated {
            get {
                return ResourceManager.GetString("NuSpecFileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &quot;{0}&quot; is obsolete and has been deleted.
        /// </summary>
        internal static string ObsoleteFolderDeleted {
            get {
                return ResourceManager.GetString("ObsoleteFolderDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; requests package &apos;{1}&apos; with version {2}, but another one version {3}.
        /// </summary>
        internal static string PackageVersionClashDueToFile {
            get {
                return ResourceManager.GetString("PackageVersionClashDueToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no project file &quot;{0}&quot;.
        /// </summary>
        internal static string ProjectFileNotFound {
            get {
                return ResourceManager.GetString("ProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top level namespace &apos;{0}&apos; does not contain any dot (&apos;.&apos;).
        /// </summary>
        internal static string TopLevelNamespaceLacksADot {
            get {
                return ResourceManager.GetString("TopLevelNamespaceLacksADot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an uncommitted change to &quot;{0}&quot;.
        /// </summary>
        internal static string UncommittedChangeTo {
            get {
                return ResourceManager.GetString("UncommittedChangeTo", resourceCulture);
            }
        }
    }
}
